# SPDX-License-Identifier: GPL-3.0-or-later
# Extracted compatibility implementation; see reference and attribution.

function init_vars() {
	declare -g sam_game_log="${SAM_GAME_LOG:-/tmp/SAM_Games.log}"
	declare -g sam_display_state_file="${SAM_STATE_FILE:-/tmp/SAM_state}"
	declare -g sam_display_owner_start=""
	declare -gl monitorenable="no"
	declare -g mrsampath="${SAM_ROOT:-/media/fat/Scripts/.MiSTer_SAM}"
	declare -g misterpath="${SAM_MISTER_ROOT:-/media/fat}"
	declare -g mrsamtmp="${SAM_TMP_ROOT:-/tmp/.SAM_tmp}"
	# Save our PID and process
	declare -g sampid="${$}"
	declare -g samprocess
	samprocess="${0##*/}"
	declare -g menuonly="Yes"
	declare -g key_activity_file="/tmp/.SAM_tmp/SAM_Keyboard_Activity"
	declare -g joy_activity_file="/tmp/.SAM_tmp/SAM_Joy_Activity"
	declare -g mouse_activity_file="/tmp/.SAM_tmp/SAM_Mouse_Activity"
	declare -g sam_menu_file="/tmp/.SAMmenu"
	declare -g brfake="$mrsamtmp/brfake"
	declare -g Artwork_only="No"
	declare -g Artwork_source="database"
	declare -g Artwork_style="box3d"
	declare -g Artwork_db_cores=""
	declare -g samini_file="${SAM_INI:-/media/fat/Scripts/MiSTer_SAM.ini}"
	declare -g samini_update_file="${mrsampath}/MiSTer_SAM.default.ini"
	declare -gi inmenu=0
	declare -gi MENU_LOADED=0
	declare -gi sam_bgmmenu=0
	declare -gi shown=0
	declare -gi coreretries=3
	declare -gi romloadfails=0
	declare -g gamelistpath="${SAM_LIST_ROOT:-/media/fat/SAM}/Gamelists"
	declare -g listroot="${SAM_LIST_ROOT:-/media/fat/SAM}"
	declare -g ratedpath="$listroot/Rated" blacklistpath="$listroot/Blacklists" ignorepath="$listroot/Ignore"
	declare -g gamelistpathtmp="${SAM_SESSION_LIST_ROOT:-/tmp/.SAM_List}"
	declare -g tmpfile="$gamelistpathtmp/tmpfile"
	declare -g tmpfile2="$gamelistpathtmp/tmpfile2"
	declare -g tmpfilefilter="$gamelistpathtmp/tmpfilefilter"
	declare -g corelistfile="$gamelistpathtmp/corelist"
	declare -g core_count_file="/tmp/.SAM_tmp/sv_corecount"
	declare -gi disablecoredel="0"
	declare -gi gametimer=120
	declare -gl corelist="amiga,amigacd32,ao486,arcade,atari2600,atari5200,atari7800,atarilynx,c64,cdi,coco2,colecovision,intellivision,fds,gb,gbc,gba,genesis,gg,jaguar,megacd,n64,neogeo,neogeocd,nes,s32x,saturn,sgb,sms,snes,stv,tgfx16,tgfx16cd,3do,vectrex,wonderswan,wonderswancolor,psx,x68k,mgls"
	declare -gl corelistall="${corelist}"
	declare -gl skipmessage="Yes"
	declare -gl disablebootrom="no"
	declare -gl skiptime="10"
	declare -gl norepeat="Yes"
	declare -gl disable_blacklist="No"
	declare -gl amigaselect="All"
	declare -gl m82="no"
	declare -gi m82_game_timer=180      # How long (secs) user can play in M82 play mode
	declare -gl m82_muted="no"          # Whether to mute audio during M82 demo/bios
	declare -g  m82_phase_file="/tmp/.SAM_tmp/m82_phase"  # "bios" or "game"
	declare -gl sam_goat_list="no"
	declare -gl mute="No"
	declare -gi update_done=0
	declare -gl ignore_when_skip="no"
	declare -gl coreweight="No"
	declare -gi gamelists_created=0
	declare -gl playcurrentgame="No"
	declare -gl kids_safe="No"
	declare -gl rating="No"
	declare -gl dupe_mode="normal"
	declare -gl listenmouse="Yes"
	declare -gl listenkeyboard="Yes"
	declare -gl listenjoy="Yes"
	declare -gl mgls_dirs=""
	declare -g repository_url="https://github.com/mrchrisster/MiSTer_SAM"
	declare -g branch="test"
	declare -g raw_base="https://raw.githubusercontent.com/mrchrisster/MiSTer_SAM/${branch}"
	declare -gi counter=0
	declare -gA corewc
	declare -gA corep
	declare -g userstartup="/media/fat/linux/user-startup.sh"
	declare -g userstartuptpl="/media/fat/linux/_user-startup.sh"
	declare -gl useneogeotitles="Yes"
	declare -gl arcadeorient
	declare -gl checkzipsondisk="No"
	declare -gl force_zip_scan="No"
	declare -gl check_for_new_games="Yes"
    declare -gl update_gamelists_during_play="No"
	declare -gi bootsleep="60"
	declare -gi totalgamecount
	# ======== DEBUG VARIABLES ========
	declare -gl samdebug="No"
	declare -gl samdebuglog="No"
	# ======== BGM =======
	declare -gl bgm="No"
	declare -gl bgmplay="Yes"
	declare -gl bgmstop="Yes"
	declare -gi gvoladjust="0"

	# ======== TTY2OLED =======
	declare -g TTY_cmd_pipe="${mrsamtmp}/TTY_cmd_pipe"
	declare -gl ttyenable="No"
	declare -gi ttyupdate_pause=10
	declare -g tty_currentinfo_file=${mrsamtmp}/tty_currentinfo
	declare -g tty_sleepfile="/tmp/tty2oled_sleep"
	declare -gl ttyname_cleanup="no"
	declare -gA tty_currentinfo=(
		[core_pretty]=""
		[name]=""
		[core]=""
		[date]=0
		[counter]=0
		[name_scroll]=""
		[name_scroll_position]=0
		[name_scroll_direction]=1
		[update_pause]=${ttyupdate_pause}
	)

	# ======== SAMVIDEO =======
	declare -gA SV_TVC_CL
	declare -gl samvideo
	declare -gl samvideo_freq
	declare -gl samvideo_output="hdmi"
	declare -gl samvideo_source
	declare -gl samvideo_tvc_cdi
	declare -gl samvideo_tvc
	declare -gl download_manager="yes"
	declare -gl sv_aspectfix_vmode
	declare -gl sv_inimod="yes"
	declare -gl sv_inibackup="yes"
	declare -gl keep_local_copy="yes"
	declare -gl do_fast_chd_fill="no"
	declare -gl new_only_chd="no"

	declare -g sv_inibackup_file="/media/fat/MiSTer.ini.sam_backup"
	declare -g samvideo_crtmode="video_mode=640,16,64,80,240,1,3,14,12380"
	declare -g samvideo_displaywait="2"
	declare -g tmpvideo="/tmp/SAMvideo.mp4"
	declare -g ini_file="$misterpath/MiSTer.ini"
	declare -g ini_contents=""
	declare -g sv_ini_temp_file="/tmp/MiSTer.ini.samvideo"
	declare -g sv_core="/tmp/.SAM_tmp/sv_core"
	declare -g sv_gametimer_file="/tmp/.SAM_tmp/sv_gametimer"
	declare -g sv_loadcounter=0
	declare -g samvideo_path="/media/fat/video"
	declare -g sv_archive_cdi="https://archive.org/download/mister-sam-cdi-vcd-commercials/mister-sam-cdi-vcd-commercials_files.xml"
	declare -g sv_archive_hdmilist="https://archive.org/download/640x480_videogame_commercials/640x480_videogame_commercials_files.xml"
	declare -g sv_archive_crtlist="https://archive.org/download/640x240_videogame_commercials/640x240_videogame_commercials_files.xml"


	# ======== CORE PATHS RBF ========
	declare -g amigapathrbf="_Computer"
	declare -g amigacd32pathrbf="_Computer"
	declare -g arcadepathrbf="_Arcade"
	declare -g ao486pathrbf="_Computer"
	declare -g atari2600pathrbf="_Console"
	declare -g atari5200pathrbf="_Console"
	declare -g atari7800pathrbf="_Console"
	declare -g atarilynxpathrbf="_Console"
	declare -g c64pathrbf="_Computer"
	declare -g cdipathrbf="_Console"
	declare -g coco2pathrbf="_Computer"
	declare -g colecovisionpathrbf="_Console"
	declare -g intellivisionpathrbf="_Console"
	declare -g fdspathrbf="_Console"
	declare -g gbpathrbf="_Console"
	declare -g gbcpathrbf="_Console"
	declare -g gbapathrbf="_Console"
	declare -g genesispathrbf="_Console"
	declare -g ggpathrbf="_Console"
	declare -g jaguarpathrbf="_Console"
	declare -g threedopathrbf="_Console"
	declare -g megacdpathrbf="_Console"
	declare -g n64pathrbf="_Console"
	declare -g neogeopathrbf="_Console"
	declare -g neogeocdpathrbf="_Console"
	declare -g nespathrbf="_Console"
	declare -g s32xpathrbf="_Console"
	declare -g saturnpathrbf="_Console"
	declare -g sgbpathrbf="_Console"
	declare -g smspathrbf="_Console"
	declare -g snespathrbf="_Console"
	declare -g stvpathrbf="_Arcade"
	declare -g tgfx16pathrbf="_Console"
	declare -g tgfx16cdpathrbf="_Console"
    declare -g psxpathrbf="_Console"
    declare -g vectrexpathrbf="_Console"
    declare -g wonderswanpathrbf="_Console"
    declare -g wonderswancolorpathrbf="_Console"
    declare -g x68kpathrbf="_Computer"


	special_cores=(amiga ao486 x68k) #amigacd32 uses normal gamelists since it's chd files

	declare -g configpath="${SAM_CONFIG_ROOT:-/media/fat/config}"
}

function init_data() {
	# Core to long name mappings
	declare -gA CORE_PRETTY=(
		["amiga"]="Commodore Amiga"
		["arcade"]="MiSTer Arcade"
		["amigacd32"]="Commodore Amiga CD32"
		["ao486"]="PC 486 DX-100"
		["atari2600"]="Atari 2600"
		["atari5200"]="Atari 5200"
		["atari7800"]="Atari 7800"
		["atarilynx"]="Atari Lynx"
		["c64"]="Commodore 64"
		["cdi"]="Philips CD-i"
		["coco2"]="TRS-80 Color Computer 2"
		["colecovision"]="ColecoVision"
		["intellivision"]="Mattel Intellivision"
		["fds"]="Nintendo Disk System"
		["gb"]="Nintendo Game Boy"
		["gbc"]="Nintendo Game Boy Color"
		["gba"]="Nintendo Game Boy Advance"
		["genesis"]="Sega Genesis / Megadrive"
		["gg"]="Sega Game Gear"
		["jaguar"]="Atari Jaguar"
		["3do"]="Panasonic 3DO"
		["megacd"]="Sega CD / Mega CD"
		["n64"]="Nintendo N64"
		["neogeo"]="SNK NeoGeo"
		["neogeocd"]="SNK NeoGeo CD"
		["nes"]="Nintendo Entertainment System"
		["s32x"]="Sega 32x"
		["saturn"]="Sega Saturn"
		["sgb"]="Super Gameboy"
		["sms"]="Sega Master System"
		["snes"]="Super Nintendo"
		["stv"]="Sega Titan Video"
		["tgfx16"]="NEC TurboGrafx-16 "
        ["tgfx16cd"]="NEC TurboGrafx-16 CD"
        ["psx"]="Sony Playstation"
        ["vectrex"]="GCE Vectrex"
        ["wonderswan"]="Bandai WonderSwan"
        ["wonderswancolor"]="Bandai WonderSwan Color"
        ["x68k"]="Sharp X68000"
        ["mgls"]="Custom MGL"
	)

	# Core to file extension mappings
	declare -glA CORE_EXT=(
		["amigacd32"]="chd,cue"
		["ao486"]="mgl"
		["arcade"]="mra"
		["atari2600"]="a26"
		["atari5200"]="a52,car"
		["atari7800"]="a78"
		["atarilynx"]="lnx"
		["c64"]="crt,prg" 		# need to be tested "reu,tap,flt,rom,c1581"
		["cdi"]="chd,cue"
		["coco2"]="ccc"
		["colecovision"]="col"
		["intellivision"]="int,bin,rom"
		["fds"]="fds"
		["gb"]="gb"
		["gbc"]="gbc"
		["gba"]="gba"
		["genesis"]="md,gen"
		["gg"]="gg"
		["jaguar"]="j64,rom,bin,jag"
		["3do"]="cue,chd"
		["megacd"]="chd,cue"
		["n64"]="n64,z64"
		["neogeo"]="neo"
		["neogeocd"]="cue,chd"
		["nes"]="nes"
		["s32x"]="32x"
		["saturn"]="cue,chd"
		["sgb"]="gb,gbc"
		["sms"]="sms,sg"
		["snes"]="sfc,smc" 	 	# Should we include? "bin,bs"
		["tgfx16"]="pce,sgx"
        ["tgfx16cd"]="chd,cue"
        ["psx"]="chd,cue,exe"
        ["vectrex"]="bin"
        ["wonderswan"]="ws"
        ["wonderswancolor"]="wsc"
        ["x68k"]="mgl"
        ["mgls"]="mgl"
	)

	# Core to path mappings
	declare -gA PATHFILTER=(
		["amiga"]="${amigapathfilter}"
		["amigacd32"]="${amigacd32pathfilter}"
		["ao486"]="${ao486pathfilter}"
		["arcade"]="${arcadepathfilter}"
		["atari2600"]="${atari2600pathfilter}"
		["atari5200"]="${atari5200pathfilter}"
		["atari7800"]="${atari7800pathfilter}"
		["atarilynx"]="${atarilynxpathfilter}"
		["c64"]="${c64pathfilter}"
		["cdi"]="${cdipathfilter}"
		["coco2"]="${coco2pathfilter}"
		["colecovision"]="${colecovisionpathfilter}"
		["intellivision"]="${intellivisionpathfilter}"
		["fds"]="${fdspathfilter}"
		["gb"]="${gbpathfilter}"
		["gbc"]="${gbcpathfilter}"
		["gba"]="${gbapathfilter}"
		["genesis"]="${genesispathfilter}"
		["gg"]="${ggpathfilter}"
		["jaguar"]="${jaguarpathfilter}"
		["3do"]="${threedopathfilter}"
		["megacd"]="${megacdpathfilter}"
		["n64"]="${n64pathfilter}"
		["neogeo"]="${neogeopathfilter}"
		["neogeocd"]="${neogeocdpathfilter}"
		["nes"]="${nespathfilter}"
		["s32x"]="${s32xpathfilter}"
		["saturn"]="${saturnpathfilter}"
		["sgb"]="${sgbpathfilter}"
		["sms"]="${smspathfilter}"
		["snes"]="${snespathfilter}"
		["stv"]="${stvpathfilter}"
		["tgfx16"]="${tgfx16pathfilter}"
        ["tgfx16"]="${tgfx16pathfilter}"
        ["tgfx16cd"]="${tgfx16cdpathfilter}"
        ["psx"]="${psxpathfilter}"
        ["vectrex"]="${vectrexpathfilter}"
        ["wonderswan"]="${wonderswanpathfilter}"
        ["wonderswancolor"]="${wonderswancolorpathfilter}"
        ["x68k"]="${x68kpathfilter}"
        ["mgls"]="${mglspathfilter}"
	)


	# Core to path mappings for rbf files
	declare -gA CORE_PATH_RBF=(
		["amiga"]="${amigapathrbf}"
		["amigacd32"]="${amigacd32pathrbf}"
		["ao486"]="${ao486pathrbf}"
		["arcade"]="${arcadepathrbf}"
		["atari2600"]="${atari2600pathrbf}"
		["atari5200"]="${atari5200pathrbf}"
		["atari7800"]="${atari7800pathrbf}"
		["atarilynx"]="${atarilynxpathrbf}"
		["c64"]="${c64pathrbf}"
		["cdi"]="${cdipathrbf}"
		["coco2"]="${coco2pathrbf}"
		["colecovision"]="${colecovisionpathrbf}"
		["intellivision"]="${intellivisionpathrbf}"
		["fds"]="${fdspathrbf}"
		["gb"]="${gbpathrbf}"
		["gbc"]="${gbcpathrbf}"
		["gba"]="${gbapathrbf}"
		["genesis"]="${genesispathrbf}"
		["gg"]="${ggpathrbf}"
		["jaguar"]="${jaguarpathrbf}"
		["3do"]="${threedopathrbf}"
		["megacd"]="${megacdpathrbf}"
		["n64"]="${n64pathrbf}"
		["neogeo"]="${neogeopathrbf}"
		["neogeocd"]="${neogeocdpathrbf}"
		["nes"]="${nespathrbf}"
		["s32x"]="${s32xpathrbf}"
		["saturn"]="${saturnpathrbf}"
		["sgb"]="${sgbpathrbf}"
		["sms"]="${smspathrbf}"
		["snes"]="${snespathrbf}"
        ["stv"]="${stvpathrbf}"
        ["tgfx16"]="${tgfx16pathrbf}"
        ["tgfx16cd"]="${tgfx16cdpathrbf}"
        ["psx"]="${psxpathrbf}"
        ["vectrex"]="${vectrexpathrbf}"
        ["wonderswan"]="${wonderswanpathrbf}"
        ["wonderswancolor"]="${wonderswancolorpathrbf}"
        ["x68k"]="${x68kpathrbf}"
	)

	# Can this core skip Bios/Safety warning messages
	declare -glA CORE_SKIP=(
		["amiga"]="No"
		["amigacd32"]="Yes"
		["ao486"]="No"
		["arcade"]="No"
		["atari2600"]="No"
		["atari5200"]="No"
		["atari7800"]="No"
		["atarilynx"]="No"
		["c64"]="No"
		["cdi"]="No"
		["coco2"]="No"
		["colecovision"]="No"
		["intellivision"]="Yes"
		["fds"]="Yes"
		["gb"]="No"
		["gbc"]="No"
		["gba"]="No"
		["genesis"]="No"
		["gg"]="No"
		["jaguar"]="No"
		["3do"]="Yes"
		["megacd"]="Yes"
		["n64"]="No"
		["neogeo"]="No"
		["neogeocd"]="Yes"
		["nes"]="No"
		["s32x"]="No"
		["saturn"]="Yes"
		["sgb"]="No"
		["sms"]="No"
        ["snes"]="No"
        ["stv"]="No"
        ["tgfx16"]="No"
        ["tgfx16cd"]="Yes"
        ["psx"]="No"
        ["vectrex"]="No"
        ["wonderswan"]="No"
        ["wonderswancolor"]="No"
        ["x68k"]="No"
        ["mgls"]="No"
	)


	# Core to input maps mapping
	declare -gA CORE_LAUNCH=(
		["amiga"]="Minimig"
		["amigacd32"]="Minimig"
		["ao486"]="ao486"
		["arcade"]="Arcade"
		["atari2600"]="ATARI7800"
		["atari5200"]="ATARI5200"
		["atari7800"]="ATARI7800"
		["atarilynx"]="AtariLynx"
		["c64"]="C64"
		["cdi"]="CDi"
		["coco2"]="CoCo2"
		["colecovision"]="ColecoVision"
		["intellivision"]="Intellivision"
		["fds"]="NES"
		["gb"]="GAMEBOY"
		["gbc"]="GAMEBOY"
		["gba"]="GBA"
		["genesis"]="MEGADRIVE"
		["gg"]="SMS"
		["jaguar"]="Jaguar"
		["3do"]="3DO"
		["megacd"]="MegaCD"
		["n64"]="N64"
		["neogeo"]="NEOGEO"
		["neogeocd"]="NEOGEO"
		["nes"]="NES"
		["s32x"]="S32X"
		["saturn"]="SATURN"
		["sgb"]="SGB"
		["sms"]="SMS"
		["snes"]="SNES"
		["stv"]="S-TV"
		["tgfx16"]="TGFX16"
        ["tgfx16cd"]="TGFX16"
        ["psx"]="PSX"
        ["vectrex"]="Vectrex"
        ["wonderswan"]="WonderSwan"
        ["wonderswancolor"]="WonderSwan"
        ["x68k"]="X68000"
        ["mgls"]="MGL"
	)

	# TTY2OLED Core Pic mappings
	declare -gA TTY2OLED_PIC_NAME=(
		["amiga"]="Minimig"
		["amigacd32"]="Minimig"
		["ao486"]="ao486"
		["arcade"]="Arcade"
		["atari2600"]="ATARI2600"
		["atari5200"]="ATARI5200"
		["atari7800"]="ATARI7800"
		["atarilynx"]="AtariLynx"
		["c64"]="C64"
		["cdi"]="CD-i"
		["coco2"]="CoCo2"
		["colecovision"]="ColecoVision"
		["intellivision"]="Intellivision"
		["fds"]="fds"
		["gb"]="GAMEBOY"
		["gbc"]="GAMEBOY"
		["gba"]="GBA"
		["genesis"]="MegaDrive"
		["gg"]="gamegear"
		["jaguar"]="Jaguar"
		["3do"]="3DO"
		["megacd"]="MegaCD"
		["n64"]="N64"
		["neogeo"]="NEOGEO"
		["neogeocd"]="NEOGEO"
		["nes"]="NES"
		["s32x"]="S32X"
		["saturn"]="SATURN"
		["sgb"]="SGB"
		["sms"]="SMS"
		["snes"]="SNES"
		["stv"]="S-TV"
        ["tgfx16"]="TGFX16"
        ["tgfx16cd"]="TGFX16"
        ["psx"]="PSX"
        ["vectrex"]="Vectrex"
        ["wonderswan"]="WonderSwan"
        ["wonderswancolor"]="WonderSwan"
        ["x68k"]="X68000"
        ["mgls"]="MGL"
	)

	# MGL core name settings
	declare -gA MGL_CORE=(
		["amiga"]="Minimig"
		["amigacd32"]="Minimig"
		["ao486"]="ao486"
		["arcade"]="Arcade"
		["atari2600"]="ATARI7800"
		["atari5200"]="ATARI5200"
		["atari7800"]="ATARI7800"
		["atarilynx"]="AtariLynx"
		["c64"]="C64"
		["cdi"]="CDi"
		["coco2"]="CoCo2"
		["colecovision"]="ColecoVision"
		["intellivision"]="Intellivision"
		["fds"]="NES"
		["gb"]="GAMEBOY"
		["gbc"]="GAMEBOY"
		["gba"]="GBA"
		["genesis"]="MegaDrive"
		["gg"]="SMS"
		["jaguar"]="Jaguar"
		["3do"]="3DO"
		["megacd"]="MegaCD"
		["n64"]="N64"
		["neogeo"]="NEOGEO"
		["neogeocd"]="NEOGEO"
		["nes"]="NES"
		["s32x"]="S32X"
		["saturn"]="SATURN"
		["sgb"]="SGB"
		["sms"]="SMS"
		["snes"]="SNES"
		["stv"]="S-TV"
		["tgfx16"]="TurboGrafx16"
        ["tgfx16cd"]="TurboGrafx16"
        ["psx"]="PSX"
        ["vectrex"]="Vectrex"
        ["wonderswan"]="WonderSwan"
        ["wonderswancolor"]="WonderSwan"
        ["x68k"]="X68000"
	)

	# MGL setname settings
	declare -gA MGL_SETNAME=(
		["amigacd32"]="AmigaCD32"
		["gbc"]="GBC"
		["gg"]="GameGear"
		["wonderswancolor"]="WonderSwanColor"
	)

	# MGL delay settings
	declare -giA MGL_DELAY=(
		["amiga"]="1"
		["amigacd32"]="1"
		["ao486"]="0"
		["arcade"]="2"
		["atari2600"]="1"
		["atari5200"]="1"
		["atari7800"]="1"
		["atarilynx"]="1"
		["c64"]="1"
		["cdi"]="1"
		["coco2"]="1"
		["colecovision"]="1"
		["intellivision"]="1"
		["fds"]="2"
		["gb"]="2"
		["gbc"]="2"
		["gba"]="2"
		["genesis"]="1"
		["gg"]="1"
		["jaguar"]="1"
		["3do"]="1"
		["megacd"]="1"
		["n64"]="1"
		["neogeo"]="1"
		["neogeocd"]="1"
		["nes"]="2"
		["s32x"]="1"
		["saturn"]="1"
		["sgb"]="1"
		["sms"]="1"
		["snes"]="2"
		["stv"]="2"
        ["tgfx16"]="1"
        ["tgfx16cd"]="1"
        ["psx"]="1"
        ["vectrex"]="1"
        ["wonderswan"]="1"
        ["wonderswancolor"]="1"
        ["x68k"]="1"

	)

	# MGL index settings
	declare -giA MGL_INDEX=(
		["amiga"]="0"
		["amigacd32"]="0"
		["ao486"]="2"
		["arcade"]="0"
		["atari2600"]="0"
		["atari5200"]="1"
		["atari7800"]="1"
		["atarilynx"]="1"
		["c64"]="1"
		["cdi"]="1"
		["coco2"]="1"
		["colecovision"]="1"
		["intellivision"]="1"
		["fds"]="0"
		["gb"]="0"
		["gbc"]="0"
		["gba"]="0"
		["genesis"]="0"
		["gg"]="2"
		["jaguar"]="1"
		["3do"]="1"
		["megacd"]="0"
		["n64"]="1"
		["neogeo"]="1"
		["neogeocd"]="1"
		["nes"]="0"
		["s32x"]="0"
		["saturn"]="0"
		["sgb"]="1"
		["sms"]="1"
		["snes"]="0"
		["stv"]="0"
        ["tgfx16"]="1"
        ["tgfx16cd"]="0"
        ["psx"]="1"
        ["vectrex"]="1"
        ["wonderswan"]="1"
        ["wonderswancolor"]="1"
        ["x68k"]="2"
	)

	# MGL type settings
	declare -glA MGL_TYPE=(
		["amiga"]="f"
		["amigacd32"]="f"
		["ao486"]="s"
		["arcade"]="f"
		["atari2600"]="f"
		["atari5200"]="f"
		["atari7800"]="f"
		["atarilynx"]="f"
		["c64"]="f"
		["cdi"]="s"
		["coco2"]="f"
		["colecovision"]="f"
		["intellivision"]="f"
		["fds"]="f"
		["gb"]="f"
		["gbc"]="f"
		["gba"]="f"
		["genesis"]="f"
		["gg"]="f"
		["jaguar"]="f"
		["3do"]="s"
		["megacd"]="s"
		["n64"]="f"
		["neogeo"]="f"
		["neogeocd"]="s"
		["nes"]="f"
		["s32x"]="f"
		["saturn"]="s"
		["sgb"]="f"
		["sms"]="f"
		["snes"]="f"
		["stv"]="f"
		["tgfx16"]="f"
        ["tgfx16cd"]="s"
        ["psx"]="s"
        ["vectrex"]="f"
        ["wonderswan"]="f"
        ["wonderswancolor"]="f"
        ["x68k"]="s"
	)


	# NEOGEO to long name mappings English
	declare -gA NEOGEO_PRETTY_ENGLISH=(
		["3countb"]="3 Count Bout"
		["2020bb"]="2020 Super Baseball"
		["2020bba"]="2020 Super Baseball (set 2)"
		["2020bbh"]="2020 Super Baseball (set 3)"
		["abyssal"]="Abyssal Infants"
		["alpham2"]="Alpha Mission II"
		["alpham2p"]="Alpha Mission II (prototype)"
		["androdun"]="Andro Dunos"
		["aodk"]="Aggressors of Dark Kombat"
		["aof"]="Art of Fighting"
		["aof2"]="Art of Fighting 2"
		["aof2a"]="Art of Fighting 2 (NGH-056)"
		["aof3"]="Art of Fighting 3: The Path of the Warrior"
		["aof3k"]="Art of Fighting 3: The Path of the Warrior (Korean release)"
		["b2b"]="Bang Bang Busters"
		["badapple"]="Bad Apple Demo"
		["bakatono"]="Bakatonosama Mahjong Manyuuki"
		["bangbead"]="Bang Bead"
		["bjourney"]="Blue's Journey"
		["blazstar"]="Blazing Star"
		["breakers"]="Breakers"
		["breakrev"]="Breakers Revenge"
		["brningfh"]="Burning Fight (NGH-018, US)"
		["brningfp"]="Burning Fight (prototype, older)"
		["brnngfpa"]="Burning Fight (prototype, near final, ver 23.3, 910326)"
		["bstars"]="Baseball Stars Professional"
		["bstars2"]="Baseball Stars 2"
		["bstarsh"]="Baseball Stars Professional (NGH-002)"
		["burningf"]="Burning Fight"
		["burningfh"]="Burning Fight (NGH-018, US)"
		["burningfp"]="Burning Fight (prototype, older)"
		["burningfpa"]="Burning Fight (prototype, near final, ver 23.3, 910326)"
		["cabalng"]="Cabal"
		["columnsn"]="Columns"
		["cphd"]="Crouching Pony Hidden Dragon Demo"
		["crswd2bl"]="Crossed Swords 2 (CD conversion)"
		["crsword"]="Crossed Swords"
		["ct2k3sa"]="Crouching Tiger Hidden Dragon 2003 Super Plus (The King of Fighters 2001 bootleg)"
		["ctomaday"]="Captain Tomaday"
		["cyberlip"]="Cyber-Lip"
		["diggerma"]="Digger Man"
		["doubledr"]="Double Dragon"
		["eightman"]="Eight Man"
		["fatfursp"]="Fatal Fury Special"
		["fatfurspa"]="Fatal Fury Special (NGM-058 ~ NGH-058, set 2)"
		["fatfury1"]="Fatal Fury: King of Fighters"
		["fatfury2"]="Fatal Fury 2"
		["fatfury3"]="Fatal Fury 3: Road to the Final Victory"
		["fbfrenzy"]="Football Frenzy"
		["fghtfeva"]="Fight Fever (set 2)"
		["fightfev"]="Fight Fever"
		["fightfeva"]="Fight Fever (set 2)"
		["flipshot"]="Battle Flip Shot"
		["frogfest"]="Frog Feast"
		["froman2b"]="Idol Mahjong Final Romance 2 (CD conversion)"
		["fswords"]="Fighters Swords (Korean release of Samurai Shodown III)"
		["ftfurspa"]="Fatal Fury Special (NGM-058 ~ NGH-058, set 2)"
		["galaxyfg"]="Galaxy Fight: Universal Warriors"
		["ganryu"]="Ganryu"
		["garou"]="Garou: Mark of the Wolves"
		["garoubl"]="Garou: Mark of the Wolves (bootleg)"
		["garouh"]="Garou: Mark of the Wolves (earlier release)"
		["garoup"]="Garou: Mark of the Wolves (prototype)"
		["ghostlop"]="Ghostlop"
		["goalx3"]="Goal! Goal! Goal!"
		["gowcaizr"]="Voltage Fighter Gowcaizer"
		["gpilots"]="Ghost Pilots"
		["gpilotsh"]="Ghost Pilots (NGH-020, US)"
		["gururin"]="Gururin"
		["hyprnoid"]="Hypernoid"
		["irnclado"]="Ironclad (prototype, bootleg)"
		["ironclad"]="Ironclad"
		["ironclado"]="Ironclad (prototype, bootleg)"
		["irrmaze"]="The Irritating Maze"
		["janshin"]="Janshin Densetsu: Quest of Jongmaster"
		["joyjoy"]="Puzzled"
		["kabukikl"]="Far East of Eden: Kabuki Klash"
		["karnovr"]="Karnov's Revenge"
		["kf2k2mp"]="The King of Fighters 2002 Magic Plus (bootleg)"
		["kf2k2mp2"]="The King of Fighters 2002 Magic Plus II (bootleg)"
		["kf2k2pla"]="The King of Fighters 2002 Plus (bootleg set 2)"
		["kf2k2pls"]="The King of Fighters 2002 Plus (bootleg)"
		["kf2k5uni"]="The King of Fighters 10th Anniversary 2005 Unique (The King of Fighters 2002 bootleg)"
		["kf10thep"]="The King of Fighters 10th Anniversary Extra Plus (The King of Fighters 2002 bootleg)"
		["kizuna"]="Kizuna Encounter: Super Tag Battle"
		["kof2k4se"]="The King of Fighters Special Edition 2004 (The King of Fighters 2002 bootleg)"
		["kof94"]="The King of Fighters '94"
		["kof95"]="The King of Fighters '95"
		["kof95a"]="The King of Fighters '95 (NGM-084, alt board)"
		["kof95h"]="The King of Fighters '95 (NGH-084)"
		["kof96"]="The King of Fighters '96"
		["kof96h"]="The King of Fighters '96 (NGH-214)"
		["kof97"]="The King of Fighters '97"
		["kof97h"]="The King of Fighters '97 (NGH-2320)"
		["kof97k"]="The King of Fighters '97 (Korean release)"
		["kof97oro"]="The King of Fighters '97 Chongchu Jianghu Plus 2003 (bootleg)"
		["kof97pls"]="The King of Fighters '97 Plus (bootleg)"
		["kof98"]="The King of Fighters '98: The Slugfest"
		["kof98a"]="The King of Fighters '98: The Slugfest (NGM-2420, alt board)"
		["kof98h"]="The King of Fighters '98: The Slugfest (NGH-2420)"
		["kof98k"]="The King of Fighters '98: The Slugfest (Korean release)"
		["kof98ka"]="The King of Fighters '98: The Slugfest (Korean release, set 2)"
		["kof99"]="The King of Fighters '99: Millennium Battle"
		["kof99e"]="The King of Fighters '99: Millennium Battle (earlier release)"
		["kof99h"]="The King of Fighters '99: Millennium Battle (NGH-2510)"
		["kof99k"]="The King of Fighters '99: Millennium Battle (Korean release)"
		["kof99p"]="The King of Fighters '99: Millennium Battle (prototype)"
		["kof2000"]="The King of Fighters 2000"
		["kof2000n"]="The King of Fighters 2000"
		["kof2001"]="The King of Fighters 2001"
		["kof2001h"]="The King of Fighters 2001 (NGH-2621)"
		["kof2002"]="The King of Fighters 2002"
		["kof2002b"]="The King of Fighters 2002 (bootleg)"
		["kof2003"]="The King of Fighters 2003"
		["kof2003h"]="The King of Fighters 2003 (NGH-2710)"
		["kof2003ps2"]="The King of Fighters 2003 (PS2)"
		["kog"]="King of Gladiators (The King of Fighters '97 bootleg)"
		["kotm"]="King of the Monsters"
		["kotm2"]="King of the Monsters 2: The Next Thing"
		["kotm2p"]="King of the Monsters 2: The Next Thing (prototype)"
		["kotmh"]="King of the Monsters (set 2)"
		["lans2004"]="Lansquenet"
		["lastblad"]="The Last Blade"
		["lastbladh"]="The Last Blade (NGH-2340)"
		["lastbld2"]="The Last Blade 2"
		["lasthope"]="Last Hope"
		["lastsold"]="The Last Soldier"
		["lbowling"]="League Bowling"
		["legendos"]="Legend of Success Joe"
		["lresort"]="Last Resort"
		["lresortp"]="Last Resort (prototype)"
		["lstbladh"]="Last Blade (NGH-2340)"
		["magdrop2"]="Magical Drop II"
		["magdrop3"]="Magical Drop III"
		["maglord"]="Magician Lord"
		["maglordh"]="Magician Lord (NGH-005)"
		["mahretsu"]="Mahjong Kyo Retsuden"
		["marukodq"]="Chibi Marukochan Deluxe Quiz"
		["matrim"]="Power Instinct Matrimelee"
		["miexchng"]="Money Puzzle Exchanger"
		["minasan"]="Minasan no Okagesamadesu! Dai Sugoroku Taikai"
		["montest"]="Monitor Test ROM"
		["moshougi"]="Shougi no Tatsujin: Master of Syougi"
		["ms4plus"]="Metal Slug 4 Plus (bootleg)"
		["mslug"]="Metal Slug: Super Vehicle-001"
		["mslug2"]="Metal Slug 2: Super Vehicle-001/II"
		["mslug2t"]="Metal Slug 2 Turbo (hack)"
		["mslug3"]="Metal Slug 3"
		["mslug3b6"]="Metal Slug 6 (Metal Slug 3 bootleg)"
		["mslug3h"]="Metal Slug 3 (NGH-2560)"
		["mslug4"]="Metal Slug 4"
		["mslug4h"]="Metal Slug 4 (NGH-2630)"
		["mslug5"]="Metal Slug 5"
		["mslug5h"]="Metal Slug 5 (NGH-2680)"
		["mslug6"]="Metal Slug 6 (Metal Slug 3 bootleg)"
		["mslugx"]="Metal Slug X: Super Vehicle-001"
		["mutnat"]="Mutation Nation"
		["nam1975"]="NAM-1975"
		["nblktigr"]="Neo Black Tiger"
		["ncombat"]="Ninja Combat"
		["ncombath"]="Ninja Combat (NGH-009)"
		["ncommand"]="Ninja Commando"
		["neobombe"]="Neo Bomberman"
		["neocup98"]="Neo-Geo Cup 98: The Road to the Victory"
		["neodrift"]="Neo Drift Out: New Technology"
		["neofight"]="Neo Fight"
		["neomrdo"]="Neo Mr. Do!"
		["neothund"]="Neo Thunder"
		["neotris"]="NeoTRIS (free beta version)"
		["ninjamas"]="Ninja Master's"
		["nitd"]="Nightmare in the Dark"
		["nitdbl"]="Nightmare in the Dark (bootleg)"
		["nsmb"]="New Super Mario Bros."
		["overtop"]="OverTop"
		["panicbom"]="Panic Bomber"
		["pbbblenb"]="Puzzle Bobble (bootleg)"
		["pbobbl2n"]="Puzzle Bobble 2"
		["pbobblen"]="Puzzle Bobble"
		["pbobblenb"]="Puzzle Bobble (bootleg)"
		["pgoal"]="Pleasure Goal"
		["pnyaa"]="Pochi and Nyaa"
		["popbounc"]="Pop 'n Bounce"
		["preisle2"]="Prehistoric Isle 2"
		["pspikes2"]="Power Spikes II"
		["pulstar"]="Pulstar"
		["puzzldpr"]="Puzzle De Pon! R!"
		["puzzledp"]="Puzzle De Pon!"
		["quizdai2"]="Quiz Meitantei Neo & Geo: Quiz Daisousa Sen part 2"
		["quizdais"]="Quiz Daisousa Sen: The Last Count Down"
		["quizdask"]="Quiz Salibtamjeong: The Last Count Down (Korean localized Quiz Daisousa Sen)"
		["quizkof"]="Quiz King of Fighters"
		["quizkofk"]="Quiz King of Fighters (Korean release)"
		["ragnagrd"]="Ragnagard"
		["rbff1"]="Real Bout Fatal Fury"
		["rbff1a"]="Real Bout Fatal Fury (bug fix revision)"
		["rbff2"]="Real Bout Fatal Fury 2: The Newcomers"
		["rbff2h"]="Real Bout Fatal Fury 2: The Newcomers (NGH-2400)"
		["rbff2k"]="Real Bout Fatal Fury 2: The Newcomers (Korean release)"
		["rbffspck"]="Real Bout Fatal Fury Special (Korean release)"
		["rbffspec"]="Real Bout Fatal Fury Special"
		["rbffspeck"]="Real Bout Fatal Fury Special (Korean release)"
		["ridhero"]="Riding Hero"
		["ridheroh"]="Riding Hero (set 2)"
		["roboarma"]="Robo Army (NGM-032 ~ NGH-032)"
		["roboarmy"]="Robo Army"
		["roboarmya"]="Robo Army (NGM-032 ~ NGH-032)"
		["rotd"]="Rage of the Dragons"
		["rotdh"]="Rage of the Dragons (NGH-2640?)"
		["s1945p"]="Strikers 1945 Plus"
		["samsh5fe"]="Samurai Shodown V Special Final Edition"
		["samsh5pf"]="Samurai Shodown V Perfect"
		["samsh5sp"]="Samurai Shodown V Special"
		["samsh5sph"]="Samurai Shodown V Special (2nd release, less censored)"
		["samsh5spho"]="Samurai Shodown V Special (1st release, censored)"
		["samsho"]="Samurai Shodown"
		["samsho2"]="Samurai Shodown II"
		["samsho2k"]="Saulabi Spirits (Korean release of Samurai Shodown II)"
		["samsho2ka"]="Saulabi Spirits (Korean release of Samurai Shodown II, set 2)"
		["samsho3"]="Samurai Shodown III"
		["samsho3h"]="Samurai Shodown III (NGH-087)"
		["samsho4"]="Samurai Shodown IV: Amakusa's Revenge"
		["samsho4k"]="Pae Wang Jeon Seol: Legend of a Warrior"
		["samsho5"]="Samurai Shodown V"
		["samsho5b"]="Samurai Shodown V (bootleg)"
		["samsho5h"]="Samurai Shodown V (NGH-2700)"
		["samsho5x"]="Samurai Shodown V (XBOX version hack)"
		["samshoh"]="Samurai Shodown (NGH-045)"
		["savagere"]="Savage Reign"
		["sbp"]="Super Bubble Pop"
		["scbrawlh"]="Soccer Brawl (NGH-031)"
		["sdodgeb"]="Super Dodge Ball"
		["sengoku"]="Sengoku"
		["sengoku2"]="Sengoku 2"
		["sengoku3"]="Sengoku 3"
		["sengokuh"]="Sengoku (NGH-017, US)"
		["shcktroa"]="Shock Troopers (set 2)"
		["shocktr2"]="Shock Troopers: 2nd Squad"
		["shocktro"]="Shock Troopers"
		["shocktroa"]="Shock Troopers (set 2)"
		["smbng"]="New Super Mario Bros. Demo"
		["smsh5sph"]="Samurai Shodown V Special (2nd release, less censored)"
		["smsh5spo"]="Samurai Shodown V Special (1st release, censored)"
		["smsho2k2"]="Saulabi Spirits (Korean release of Samurai Shodown II, set 2)"
		["socbrawl"]="Soccer Brawl"
		["socbrawlh"]="Soccer Brawl (NGH-031)"
		["sonicwi2"]="Aero Fighters 2"
		["sonicwi3"]="Aero Fighters 3"
		["spinmast"]="Spinmaster"
		["ssideki"]="Super Sidekicks"
		["ssideki2"]="Super Sidekicks 2: The World Championship"
		["ssideki3"]="Super Sidekicks 3: The Next Glory"
		["ssideki4"]="The Ultimate 11: The SNK Football Championship"
		["stakwin"]="Stakes Winner"
		["stakwin2"]="Stakes Winner 2"
		["strhoop"]="Street Hoop / Street Slam"
		["superspy"]="The Super Spy"
		["svc"]="SNK vs. Capcom: SVC Chaos"
		["svccpru"]="SNK vs. Capcom Remix Ultra"
		["svcplus"]="SNK vs. Capcom Plus (bootleg)"
		["svcsplus"]="SNK vs. Capcom Super Plus (bootleg)"
		["teot"]="The Eye of Typhoon: Tsunami Edition"
		["tetrismn"]="Tetris"
		["tophuntr"]="Top Hunter: Roddy & Cathy"
		["tophuntrh"]="Top Hunter: Roddy & Cathy (NGH-046)"
		["totc"]="Treasure of the Caribbean"
		["tpgolf"]="Top Player's Golf"
		["tphuntrh"]="Top Hunter: Roddy & Cathy (NGH-046)"
		["trally"]="Thrash Rally"
		["turfmast"]="Neo Turf Masters"
		["twinspri"]="Twinkle Star Sprites"
		["tws96"]="Tecmo World Soccer '96"
		["twsoc96"]="Tecmo World Soccer '96"
		["viewpoin"]="Viewpoint"
		["wakuwak7"]="Waku Waku 7"
		["wh1"]="World Heroes"
		["wh1h"]="World Heroes (ALH-005)"
		["wh1ha"]="World Heroes (set 3)"
		["wh2"]="World Heroes 2"
		["wh2j"]="World Heroes 2 Jet"
		["whp"]="World Heroes Perfect"
		["wjammers"]="Windjammers"
		["wjammss"]="Windjammers Supersonic"
		["xenocrisis"]="Xeno Crisis"
		["zedblade"]="Zed Blade"
		["zintrckb"]="ZinTricK"
		["zintrkcd"]="ZinTricK (CD conversion)"
		["zupapa"]="Zupapa!"
	)

	declare -glA SV_TVC=(
		["arcade"]="arcade"
		["atari2600"]="atari vcs"
		["atari5200"]="atari 5200"
		["atari7800"]="atari 7800"
		["atarilynx"]="atari lynx"
		["cdi"]="cdi"
                ["3do"]="3do"
		["gb"]="gb\|game boy"
		["gbc"]="gb\|game boy"
		["genesis"]="genesis"
		["gg"]="sega game"
		["intellivision"]="intellivision"
		["megacd"]="megacd"
		["n64"]="n64-\|n64"
		["neogeo"]="neogeo"
		["nes"]="^nes-\| nes"
		["psx"]="psx\|playstation"
		["s32x"]="sega 32x"
		["saturn"]="sega saturn"
		["sgb"]="super game boy\|gb-super game boy\|snes-super game boy"
		["sms"]="sega master"
		["snes"]="snes"
		["tgfx16"]="turboduo\|turbografx-16"
		["tgfx16cd"]="turboduo"
	)

	RATED_FILES=(
		amiga_rated.txt
		ao486_rated.txt
		arcade_rated.txt
		fds_rated.txt
		gb_rated.txt
		gba_rated.txt
		gbc_rated.txt
		genesis_rated.txt
		gg_rated.txt
		megacd_rated.txt
		n64_mature.txt
		n64_rated.txt
		neogeo_rated.txt
		nes_rated.txt
		psx_rated.txt
		saturn_mature.txt
		saturn_rated.txt
		sms_rated.txt
		snes_rated.txt
		tgfx16_rated.txt
		tgfx16cd_mature.txt
		tgfx16cd_rated.txt
	)

	BLACKLIST_FILES=(
		amiga_blacklist.txt
		arcade_blacklist.txt
		fds_blacklist.txt
		gba_blacklist.txt
		genesis_blacklist.txt
		megacd_blacklist.txt
		n64_blacklist.txt
		neogeo_blacklist.txt
		nes_blacklist.txt
		psx_blacklist.txt
		s32x_blacklist.txt
		sms_blacklist.txt
		snes_blacklist.txt
		tgfx16_blacklist.txt
		tgfx16cd_blacklist.txt
	)

}

function read_samini() {
	if [ ! -f "${samini_file}" ]; then
        echo "Creating SAM INI from installed defaults."
        cp "$samini_update_file" "$samini_file" || return 1
	fi
	source "${samini_file}"
    [[ "${sam_modules_loaded:-0}" != 1 ]] || sam_module_config_dirty=1
    sam_config_paths

	declare -g raw_base="https://raw.githubusercontent.com/mrchrisster/MiSTer_SAM/${branch}"

	#corelist=("$(echo "${corelist[@]}" | tr ',' ' ' | tr -s ' ')")
	IFS=',' read -ra corelist <<< "${corelist}"
	IFS=',' read -ra corelistall <<< "${corelistall}"

	#BGM mode
	if [ "${bgm}" == "yes" ]; then
		mute="core"
	fi


}

function update_samini() {
	[ ! -f /media/fat/Scripts/.config/downloader/downloader.log ] && return
	[ ! -f ${samini_file} ] && return
	if [[ "$(cat /media/fat/Scripts/.config/downloader/downloader.log | grep -c "MiSTer_SAM.default.ini")" != "0" ]] && [ "${samini_update_file}" -nt "${samini_file}" ]; then
		echo "New MiSTer_SAM.ini version downloaded from update_all. Merging with new ini."
		echo "Backing up MiSTer_SAM.ini to MiSTer_SAM.ini.bak"
		cp "${samini_file}" "${samini_file}".bak
		echo -n "Merging ini values.."
		# In order for the following awk script to replace variable values, we need to change our ASCII art from "=" to "-"
		sed -i 's/==/--/g' "${samini_file}"
		sed -i 's/-=/--/g' "${samini_file}"
		#awk -F= 'NR==FNR{a[$1]=$0;next}($1 in a){$0=a[$1]}1' "${samini_file}" "${samini_update_file}" >/tmp/MiSTer_SAM.tmp && cp -f --force /tmp/MiSTer_SAM.tmp "${samini_file}"

		echo "Done."
	fi

}

samini_mod() {
  local key="$1"
  local value="$2"
  local file="${3:-/media/fat/Scripts/MiSTer_SAM.ini}"
  local formatted="${key}=\"${value}\""

  if grep -q "^${key}=" "$file"; then
    sed -i "/^${key}=/c\\${formatted}" "$file"
  else
    echo "$formatted" >> "$file"
  fi
}

# MiSTer.ini subfolders are literal configuration, never shell text.
sam_config_paths() {
    local line key value base="${SAM_CONFIG_ROOT:-$misterpath/config}"
    cfgcore_configpath= cfgarcade_configpath=
    if [[ -r "$ini_file" ]]; then
        while IFS= read -r line; do
            [[ "$line" == *=* ]] || continue
            key="${line%%=*}" key="${key//[[:space:]]/}"
            case "$key" in cfgcore_subfolder|cfgarcade_subfolder) ;;
                *) continue ;; esac
            value="${line#*=}" value="${value//\"/}"
            value="${value#"${value%%[![:space:]]*}"}" value="${value%"${value##*[![:space:]]}"}"
            [[ -n "$value" ]] || continue
            if [[ "$key" == cfgcore_subfolder && -z "$cfgcore_configpath" ]]; then cfgcore_configpath="$base/$value"; fi
            if [[ "$key" == cfgarcade_subfolder && -z "$cfgarcade_configpath" ]]; then cfgarcade_configpath="$base/$value"; fi
        done < "$ini_file"
    fi
    configpath="${cfgcore_configpath:-$base}"
}
