#!/bin/bash

#======== INI VARIABLES ========
# Change these in the INI file

#======== GLOBAL VARIABLES =========
declare -g mrsampath="/media/fat/Scripts/.MiSTer_SAM"
declare -g misterpath="/media/fat"

#======== DEBUG VARIABLES ========
samquiet="Yes"
samdebug="No"
samtrace="No"

#======== LOCAL VARIABLES ========
samtimeout=60
startupsleep="Yes"
menuonly="Yes"
monitoronly="No"

#========= PARSE INI =========
# Read INI, Check for mount point presence
while ! test -d /media/fat/
do
        sleep 1
        count=`expr $count + 1`
        if test $count -eq 30; then
                echo " Mount timed out!"
                exit 1
                fi
done

if [ -f "${misterpath}/Scripts/MiSTer_SAM.ini" ]; then
        source "${misterpath}/Scripts/MiSTer_SAM.ini"
fi

# Remove trailing slash from paths
for var in mrsampath misterpath arcadepath gbapath genesispath megacdpath neogeopath nespath snespath tgfx16path tgfx16cdpath; do
        declare -g ${var}="${!var%/}"
done

# This is triggered by MiSTer_SAM_on.sh when we're not running in screen saver mode
if [ "${1,,}" == "monitoronly" ]; then
        monitoronly="Yes"
        startupsleep="No"
fi


# This is triggered by MiSTer_SAM_on.sh when we're doing initial installation
if [ "${1,,}" == "quickstart" ]; then
        startupsleep="No"
fi


#======== FUNCTIONS ========
function sam_jsmonitor() {
        # Reset trigger file
        echo "" |>/tmp/.SAM_Joy_Change
        # Monitor joystick devices for changes
        inotifywait --quiet --monitor --event create --event delete /dev/input/ --outfile /tmp/.SAM_Joy_Change &
}


#======== Start ========
# Kill running process
pids=$(pidof -o $$ $(basename -- ${0}))
if [ ! -z "pids" ]; then
        echo -n " Removing other instances of $(basename -- ${0})..."
        kill -9 ${pids} &>/dev/null
        wait ${pids} &>/dev/null
        echo " Done!"
fi

# Kill old activity processes
echo -n " Stopping activity monitoring..."
killall -q -9 MiSTer_SAM_joy.py
killall -q -9 MiSTer_SAM_mouse.sh
killall -q -9 MiSTer_SAM_keyboard.sh
killall -q -9 xxd
kill -9 $(ps | grep "inotifywait" | grep "SAM_Joy_Change" | cut --fields=2 --only-delimited --delimiter=' ')
echo " Done!"

# Convert seconds to minutes
samtimeout=$(echo - | awk -v t=${samtimeout} '{print t/60}')


#======== DEBUG OUTPUT =========
if [ "${samtrace,,}" == "yes" ]; then
        echo "********************************************************************************"
        #======== GLOBAL VARIABLES =========
        echo " mrsampath: ${mrsampath}"
        echo " misterpath: ${misterpath}"
        #======== LOCAL VARIABLES ========
        echo " commandline: ${@}"
        echo " samtimeout: ${samtimeout}"
        echo " startupsleep: ${startupsleep}"
        echo " menuonly: ${menuonly}"
        echo " monitoronly: ${monitoronly}"
        echo "********************************************************************************"
fi

echo " Starting MiSTer Super Attract Mode..."
# Start monitoring for device changes
if [ "${samquiet,,}" == "no" ]; then echo -n " Starting joystick change monitor..."; fi
sam_jsmonitor
if [ "${samquiet,,}" == "no" ]; then echo " Done!"; fi

# Spawn Joystick monitoring process per detected joystick device
shopt -s nullglob
for joystick in /dev/input/js*; do
        echo " Monitoring controller ${joystick}..."
        "${mrsampath}/MiSTer_SAM_joy.py" "${joystick}" 2>/dev/null &
done
shopt -u nullglob

# Spawn Mouse monitoring process
echo " Monitoring mouse activity..."
"${mrsampath}/MiSTer_SAM_mouse.sh" 2>/dev/null &

# Spawn Keyboard monitoring per detected keyboard device
for keyboard in $(dmesg --decode --level info --kernel --color=never --notime --nopager | grep -e 'Keyboard' | grep -Eo 'hidraw[0-9]+'); do
        echo " Monitoring keyboard ${keyboard}..."
        "${mrsampath}/MiSTer_SAM_keyboard.sh" "${keyboard}" 2>/dev/null &
done
# TODO - Detect keyboard device changes

# Spawn Log deletion process to make sure we don't run out of space in /tmp
echo "Log deletion process starting..."

cat <<\EOF > /tmp/logdelete.sh
while :; do
sleep 3600
rm `ls -at /tmp/.SAMshell* | tail -n +2`
done
EOF
chmod +x /tmp/logdelete.sh
"/tmp/logdelete.sh" 2>/dev/null &

# Startup done
echo " Done!"


# Wait for system startup - clock synchronization
if [ "${startupsleep,,}" == "yes" ]; then
        echo -n " Waiting 60 seconds for system startup..."
        sleep 60
        echo " Done!"
        echo " MiSTer SAM enabled!"
        echo " Please wait for startup"
fi

# Reset activity triggers
echo "" |>/tmp/.SAM_Joy_Activity
echo "" |>/tmp/.SAM_Mouse_Activity
echo "" |>/tmp/.SAM_Keyboard_Activity


#======== MAIN LOOP ========
while :; do
        # If we detect a change to connected joysticks:
        # Compare devices and monitoring processes
        # Make lists of what to add and what to stop monitoring
        if [ -s /tmp/.SAM_Joy_Change ]; then
                #echo " Device change(s) detected!"
                # Wait for devices to stabilize
                sleep 1

                # Init arrays
                declare -a jsdevices=()
                declare -a jsadd=()
                declare -a jsmonitors=()
                declare -a jsdel=()

                # Make a list of all js devices on system
                shopt -s nullglob
                for joystick in /dev/input/js*; do
                        jsdevices+=( "${joystick}" )
                        jsadd+=( "${joystick}" )
                done
                shopt -u nullglob

                if [ "${samtrace,,}" = "yes" ]; then
                        echo "jsdevices: ${jsdevices[@]}"
                        echo "jsadd: ${jsadd[@]}"
                fi

                # Make a list of all running js monitoring processes' jsdevices - so we don't have to track a list on disk somewhere
                for joystick in $(ps -o args | grep -e 'MiSTer_SAM_joy.py' | grep -oE '/dev/input/js[0-9]' | sort -u); do
                        jsmonitors+=( "${joystick}" )
                        jsdel+=( "${joystick}" )
                done
                if [ "${samtrace,,}" = "yes" ]; then
                        echo "jsmonitors: ${jsmonitors[@]}"
                        echo "jsdel: ${jsdel[@]}"
                fi

                # Make list of additional devices to monitor
                for joystick in ${jsmonitors[@]}; do
                        jsadd=( "${jsadd[@]/${joystick}}" )
                done
                jsadd=( "${jsadd[@]//[[:space:]]/}" )

                # Make list of removed devices to stop monitoring
                for joystick in ${jsdevices[@]}; do
                        jsdel=( "${jsdel[@]/${joystick}}" )
                done
                jsdel=( "${jsdel[@]//[[:space:]]/}" )
                if [ "${samtrace,,}" = "yes" ]; then
                        echo "jsadd: ${jsadd[@]}"
                        echo "jsdel: ${jsdel[@]}"
                fi

                # Add newly detected joystick monitoring
                for joystick in ${jsadd[@]}; do
                        if [ ! -z "${joystick}" ]; then
                                echo -n " Monitoring new joystick: ${joystick}..."
                                "${mrsampath}/MiSTer_SAM_joy.py" "${joystick}" 2>/dev/null &
                                echo " Done!"
                        fi
                done

                # Stop removed joystick monitoring
                for joystick in ${jsdel[@]}; do
                        if [ ! -z "${joystick}" ]; then
                                echo -n " Monitoring stopping for joystick: ${joystick}..."
                                        for otherpid in $(ps -o pid,args | grep -e 'MiSTer_SAM_joy.py' | grep -e "${joystick}" | awk '{ print $1 }'); do
                                                kill -9 ${otherpid}
                                                wait ${otherpid} &>/dev/null
                                        done
                                echo " Done!"
                        fi
                done

                # Reset trigger
                echo "" |>/tmp/.SAM_Joy_Change
        fi

        if [ "${menuonly,,}" == "yes" ]; then # Only start SAM from main menu
                # Check if we're at the main menu, wait 1 minute before checking activity
                if [ "$(cat /tmp/CORENAME)" == "MENU" ] && [ "$(/bin/find /tmp/CORENAME -mmin +1)" ]; then
                        # Check activity files against timeout
                        if [ "$(/bin/find /tmp/.SAM_Joy_Activity -mmin +${samtimeout})" ] && [ "$(/bin/find /tmp/.SAM_Mouse_Activity -mmin +${samtimeout})" ] && [ "$(/bin/find /tmp/.SAM_Keyboard_Activity -mmin +${samtimeout})" ]; then
                                # Reset activity triggers
                                echo "" |>/tmp/.SAM_Joy_Activity
                                echo "" |>/tmp/.SAM_Mouse_Activity
                                echo "" |>/tmp/.SAM_Keyboard_Activity

                                if [ "${monitoronly,,}" == "no" ] && [ "$(ps aux | grep -v grep | grep -c -e '{update_all.sh}')" == "0" ] && [ "$(ps aux | grep -v grep | grep -c -e '{MiSTer_SAM_on.sh}')" == "0" ]; then
                                        echo " No activity detected for ${samtimeout} minutes. SAM starting..."
                                        "/media/fat/Scripts/MiSTer_SAM_on.sh" start | tee >(split -d -b 250000 - /tmp/.SAMshell)
                                        echo " Returned from SAM."
                                fi

                                # Reset activity triggers
                                echo "" |>/tmp/.SAM_Joy_Activity
                                echo "" |>/tmp/.SAM_Mouse_Activity
                                echo "" |>/tmp/.SAM_Keyboard_Activity
                        fi
                fi
        else
                # Check activity files against timeout
                if [ "$(/bin/find /tmp/.SAM_Joy_Activity -mmin +${samtimeout})" ] && [ "$(/bin/find /tmp/.SAM_Mouse_Activity -mmin +${samtimeout})" ] && [ "$(/bin/find /tmp/.SAM_Keyboard_Activity -mmin +${samtimeout})" ]; then
                        # Reset activity triggers
                        echo "" |>/tmp/.SAM_Joy_Activity
                        echo "" |>/tmp/.SAM_Mouse_Activity
                        echo "" |>/tmp/.SAM_Keyboard_Activity

                        if [ "${monitoronly,,}" == "no" ] && [ "$(ps aux | grep -v grep | grep -c -e '{update_all.sh}')" == "0" ] && [ "$(ps aux | grep -v grep | grep -c -e '{MiSTer_SAM_on.sh}')" == "0" ]; then
                                echo " No activity detected for ${samtimeout} minutes. SAM starting..."
                                "/media/fat/Scripts/MiSTer_SAM_on.sh" start | tee >(split -d -b 250000 - /tmp/.SAMshell)
                                echo " Returned from SAM."
                        fi

                        # Reset activity triggers
                        echo "" |>/tmp/.SAM_Joy_Activity
                        echo "" |>/tmp/.SAM_Mouse_Activity
                        echo "" |>/tmp/.SAM_Keyboard_Activity
                fi
        fi
sleep 3
done
